# MIT License
#
# Copyright (c) 2023 Sophie Katz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# If any changes are made to this file, they should also be made to the
# server-routes crate and to the Thunder collection stored in
# portobello-thunder.json.

openapi: 3.0.3

info:
  title: Portobello API
  description: Primary REST API for Portobello
  version: 0.1.0

  contact:
    name: Portobello
    email: sophie@sophiekatz.us
    url: "https://github.com/sophie-katz/portobello"

  license:
    name: MIT
    url: "https://opensource.org/license/mit/"

servers:
  - url: "http://localhost:9000/api"
    description: Local development
  - url: "http://localhost:9001"
    description: Local development without Quasar proxy

paths:
  # Configuration paths
  #####################

  /configuration:
    get:
      operationId: getConfiguration
      summary: List configuration values
      description: Gets the current values of all configuration keys
      responses:
        "200":
          description: Gets the list of configuration values
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/configurationEntrySetResponse"
              example:
                - key:
                    id: 53
                    name: systems.enabled.code
                    description: Whether or not the Code system is enabled
                    type:
                      id: 1
                      name: boolean
                      description: A true/false value
                    optional: false
                    allowsMultiple: false
                    allowsUserOverride: false
                  itemsGlobal:
                    - id: 895
                      value:
                        asBoolean: true
                  user: null
                - key:
                    id: 97
                    name: theme.darkMode
                    description: Whether or not to use dark mode
                    type:
                      id: 1
                      name: boolean
                      description: A true/false value
                    optional: false
                    allowsMultiple: false
                    allowsUserOverride: true
                  itemsGlobal:
                    - id: 734
                      value:
                        asBoolean: false
                  user:
                    userId: 6b2a369d-77bb-440e-acae-d742a40473db
                    items:
                      - id: 918
                        value:
                          asBoolean: true
        "500":
          $ref: "#/components/responses/unexpectedError"

  /configuration/types:
    get:
      operationId: getConfigurationTypes
      summary: List types for configuration values
      description: Returns a map of named types for configuration values
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/configurationTypeSetResponse"
              example:
                - id: 1
                  name: boolean
                  description: A true/false value
                - id: 2
                  name: integer
                  description: A signed integer value
        "500":
          $ref: "#/components/responses/unexpectedError"

  /configuration/keys:
    get:
      operationId: getConfigurationKeys
      summary: List configuration keys
      description: Returns a map of named configuration keys
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/configurationKeySetResponse"
              example:
                - id: 53
                  name: systems.enabled.code
                  description: Whether or not the Code system is enabled
                  type:
                    id: 1
                    name: boolean
                    description: A true/false value
                  optional: false
                  allowsMultiple: false
                  allowsUserOverride: false
                - id: 97
                  name: theme.darkMode
                  description: Whether or not to use dark mode
                  type:
                    id: 1
                    name: boolean
                    description: A true/false value
                  optional: false
                  allowsMultiple: false
                  allowsUserOverride: true

        "500":
          $ref: "#/components/responses/unexpectedError"

components:
  schemas:
    # General-purpose reusable objects
    ##################################

    id:
      description: A unique id for the object
      type: integer
      nullable: false
      minimum: 1
      example: 5

    name:
      description: A human-readable name for the object
      type: string
      nullable: false
      minLength: 1

    description:
      description: A human-readable description of the object
      type: string
      nullable: false
      minLength: 1

    # Specialized reusable objects
    ##############################

    configurationTypeName:
      $ref: "#/components/schemas/name"
      description: Name of the configuration value type
      nullable: false
      pattern: "^[a-zA-Z0-9_]+$"
      examples:
        - integer
        - string

    configurationKeyName:
      $ref: "#/components/schemas/name"
      description: Name of the configuration key
      nullable: false
      pattern: "^[a-zA-Z0-9_.]+"
      example: systems.enabled.code

    userId:
      description: The id of a given user in the authentication provider service
      type: string
      nullable: false
      minLength: 1
      example: 6b2a369d-77bb-440e-acae-d742a40473db

    # Reuable response objects
    ##########################

    configurationTypeResponse:
      description: A type for the data stored in a configuration key
      type: object
      nullable: false
      required:
        - id
        - name
        - description
      properties:
        id:
          $ref: "#/components/schemas/id"
          description: Unique id of the configuration value type
        name:
          $ref: "#/components/schemas/configurationTypeName"
        description:
          $ref: "#/components/schemas/description"
          description: Name of the configuration value type
          examples:
            - A signed integer value
            - A string value
      example:
        id: 1
        name: boolean
        description: A true/false value

    configurationTypeSetResponse:
      description: A set of configuration types
      type: array
      nullable: false
      items:
        $ref: "#/components/schemas/configurationTypeResponse"
      minItems: 1
      example:
        - id: 1
          name: boolean
          description: A true/false value
        - id: 2
          name: integer
          description: A signed integer value

    configurationKeyResponse:
      description: A single configuration key
      type: object
      nullable: false
      required:
        - id
        - name
        - description
        - type
        - optional
        - allowsMultiple
        - allowsUserOverride
      properties:
        id:
          $ref: "#/components/schemas/id"
          description: Unique id of the configuration key
        name:
          $ref: "#/components/schemas/configurationKeyName"
        description:
          $ref: "#/components/schemas/description"
          description: Name of the type
          example: Whether or not the Code system is enabled
        type:
          $ref: "#/components/schemas/configurationTypeResponse"
          nullable: false
        optional:
          description: Whether or not the key is optional
          type: boolean
          nullable: false
        allowsMultiple:
          description: Whether or not the key allows multiple values in an ordered list
          type: boolean
          nullable: false
        allowsUserOverride:
          description: Whether or not the key allows users to override the configuration value in their personal profiles
          type: boolean
          nullable: false
      example:
        id: 53
        name: systems.enabled.code
        description: Whether or not the Code system is enabled
        type:
          id: 1
          name: boolean
          description: A true/false value
        optional: false
        allowsMultiple: false
        allowsUserOverride: false

    configurationKeySetResponse:
      description: A set of configuration keys
      type: array
      nullable: false
      minItems: 1
      items:
        $ref: "#/components/schemas/configurationKeyResponse"
      example:
        - id: 53
          name: systems.enabled.code
          description: Whether or not the Code system is enabled
          type:
            id: 1
            name: boolean
            description: A true/false value
          optional: false
          allowsMultiple: false
          allowsUserOverride: false
        - id: 97
          name: theme.darkMode
          description: Whether or not to use dark mode
          type:
            id: 1
            name: boolean
            description: A true/false value
          optional: false
          allowsMultiple: false
          allowsUserOverride: true

    configurationValueResponse:
      description: |-
        A value for a configuration key.

        **NOTE:** This is essentially a union of the property types.
      type: object
      nullable: false
      minProperties: 1
      maxProperties: 1
      properties:
        asBoolean:
          description: The value as a boolean
          type: boolean
          nullable: false
        asInteger:
          description: The value as an integer
          type: integer
          nullable: false
        asFloat:
          description: The value as a floating-point number
          type: number
          nullable: false
        asString:
          description: The value as a string
          type: string
          nullable: false
      example:
        asInteger: 5

    configurationEntryItemResponse:
      type: object
      description: An item containing a single value of a configuration key
      nullable: false
      required:
        - id
        - value
      properties:
        id:
          $ref: "#/components/schemas/id"
          description: Unique id of the configuration entry
        value:
          $ref: "#/components/schemas/configurationValueResponse"
          description: Value for the configuration key
      example:
        id: 895
        value:
          asBoolean: true

    configurationEntryItemSetResponse:
      description: |-
        A set of configuration entry items

        **NOTE:** `id` values may not be in order because order is stored in an implementation specific way.
      type: array
      nullable: false
      minItems: 1
      items:
        $ref: "#/components/schemas/configurationEntryItemResponse"
      example:
        - id: 154
          value:
            asString: first entry
        - id: 136
          value:
            asString: second entry

    configurationEntryUserResponse:
      type: object
      description: The part of a configuration entry that is user-specific
      nullable: true
      required:
        - userId
        - items
      properties:
        userId:
          $ref: "#/components/schemas/userId"
          description: The user id for which the entry items are set
        items:
          $ref: "#/components/schemas/configurationEntryItemSetResponse"
          description: The user-set items
      example:
        userId: 6b2a369d-77bb-440e-acae-d742a40473db
        items:
          - id: 918
            value:
              asBoolean: true

    configurationEntryResponse:
      type: object
      description: An entry representing the stored value of a configuration key
      nullable: false
      required:
        - key
        - itemsGlobal
        - user
      properties:
        key:
          $ref: "#/components/schemas/configurationKeyResponse"
          description: The configuration key of the entry
        itemsGlobal:
          $ref: "#/components/schemas/configurationEntryItemSetResponse"
          description: The globally set items
        user:
          $ref: "#/components/schemas/configurationEntryUserResponse"
      example:
        key:
          id: 97
          name: theme.darkMode
          description: Whether or not to use dark mode
          type:
            id: 1
            name: boolean
            description: A true/false value
          optional: false
          allowsMultiple: false
          allowsUserOverride: true
        itemsGlobal:
          - id: 734
            value:
              asBoolean: false
        user:
          userId: 6b2a369d-77bb-440e-acae-d742a40473db
          items:
            - id: 918
              value:
                asBoolean: true

    configurationEntrySetResponse:
      type: array
      description: A set of configuration entries
      nullable: false
      minItems: 1
      items:
        $ref: "#/components/schemas/configurationEntryResponse"
      example:
        - key:
            id: 53
            name: systems.enabled.code
            description: Whether or not the Code system is enabled
            type:
              id: 1
              name: boolean
              description: A true/false value
            optional: false
            allowsMultiple: false
            allowsUserOverride: false
          itemsGlobal:
            - id: 895
              value:
                asBoolean: true
          user: null
        - key:
            id: 97
            name: theme.darkMode
            description: Whether or not to use dark mode
            type:
              id: 1
              name: boolean
              description: A true/false value
            optional: false
            allowsMultiple: false
            allowsUserOverride: true
          itemsGlobal:
            - id: 734
              value:
                asBoolean: false
          user:
            userId: 6b2a369d-77bb-440e-acae-d742a40473db
            items:
              - id: 918
                value:
                  asBoolean: true

    errorWithMessageResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          minLength: 1
          example: could not connect to database

  responses:
    unexpectedError:
      description: An unexpected error occurred when handling the request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorWithMessageResponse"
          example:
            message: could not connect to database
